Up front extrapolation/substitution
kb-dk/kb-util pull request #61
Opened 2024-03-12 14:39 UTC by tokee

Extrapolation/substitution in `kb-util`'s `YAML` expands system properties, arguments and YAML-paths. The previous implementation performed substitution at request time, which made it difficult to implement things like the [Visitor Pattern](https://en.wikipedia.org/wiki/Visitor_pattern) extraction of sub-structures without introducing errors.

The primary implementation in this pull request is to perform a full extrapolation/substitution across the whole YAML when `setExtrapolate(true)` is called. 

Secondary fixes are
* Cleanup of Javadoc by moving `yPath` description to the class javadoc
* Changed behaviour of `getMultiple(String)` to treat the input af an `yPath` to mirror `get`. This is a breaking change, which has been discussed with @jorntx. The break was deemed acceptable as the old `getMultiple(String)` has only been part of `YAML` for a month
* `List<YAML> sub = myyaml.getList<YAML>(yPath)` now works. Previously it was necessary to call an explicit method to get a list of YAMLS: `List<YAML> sub = myyaml.getYAMLList(yPath)`
* If `get(yPath)` finds more than 1 value, an exception is thrown. The logic is that `get` is singular and multiple matches are nearly always a sign of something gone wrong. If the caller really want to use the first value from an `yPath` and is fine with ignoring subsequent values, `getMultiple(yPath)` can be used
* Extrapolation now supports indirect resolving, e.g. calling `get("foo")` for the structure below will return the user name
```yaml
foo: ${path:bar}
bar:${path:boom}
boom: ${user.name}
```

Discussion point
* The extrapolation is not done automatically. This is the same behaviour as before, but might not be the best. Should it be enabled per default?

2024-03-20 09:27 UTC, VictorHarbo requested changes
Nicely done! 
I am trying to think of situations where you don't want the extrapolation to be executed and I have a hard time thinking of situations where this is the case. Therefore I believe it would make sense if we switched the default to true.

2024-03-20 09:27 UTC, VictorHarbo commented on src/main/java/dk/kb/util/yaml/YAML.java
> +     * This method is equal to {@link #getSubMap(String)}. {@code getYAML} is preferred dut to clearer semantics.
Small typo -> due, not dut

2024-03-20 09:27 UTC, VictorHarbo commented on src/main/java/dk/kb/util/yaml/YAML.java
> +//    }
Please remove the old implementation completely. I agree with you and @jorntx on the change.

2024-03-20 09:27 UTC, VictorHarbo commented on src/main/java/dk/kb/util/yaml/YAML.java
> +            if (++iterations == 10) {
New syntax for me here! Smart one!

2024-03-20 15:09 UTC, tokee commented
> Nicely done! I am trying to think of situations where you don't want the extrapolation to be executed and I have a hard time thinking of situations where this is the case. Therefore I believe it would make sense if we switched the default to true.

I have switched this, but to maintain the option of **not** extrapolating, a lot of constructors & methods had to be overloaded with an `extrapolateSystemProperties` boolean argument.

2024-03-21 06:36 UTC, VictorHarbo commented on src/main/java/dk/kb/util/yaml/YAML.java
> +     *                                    Note that extrapolation cannot be turned off once enabled.
I really like these notes in the documentation!

2024-03-21 06:40 UTC, VictorHarbo approved these changes
This looks very good now. Merging into the branch as agreed upon last week.

2024-03-21 06:40 UTC, merged